#!/usr/bin/env bash
# Shebang for better file detection
# shellcheck enable=require-variable-braces

get_version() {
    local ver
    ver="$(realpath "$( dirname -- "${BASH_SOURCE[0]}")"/version)"
    cat "${ver}"
}

get_img_name() {
    local -a types
    types=(zip 7z xz)
    if [ -n "${DIST_PATH}" ]; then
        for i in "${types[@]}"; do
            find "${DIST_PATH}/image/" -type f -name "*.${i}" -printf "%p\n"
        done
    fi

    if [ -z "${DIST_PATH}" ]; then
        echo ""
    fi
}

DIST_VERSION="$(get_version)"
BASE_ZIP_IMG="${DIST_PATH}/image/Orangepizero3_1.0.2_debian_bookworm_server_linux6.1.31.img"
DIST_NAME="MainsailOS"

# export Variables
export DIST_NAME
export DIST_VERSION
export BASE_ZIP_IMG

BASE_ARCH="arm64"

# Image source
DOWNLOAD_URL_CHECKSUM="${DOWNLOAD_BASE_URL}/orangepi-orangepi_zero3_1500mb_bullseye.img.xz.sha256"
DOWNLOAD_URL_IMAGE="${DOWNLOAD_BASE_URL}/orangepi-orangepi_zero3_1500mb_bullseye.img.xz"

# partition resizing
BASE_ROOT_PARTITION="2"
BASE_IMAGE_ENLARGEROOT=2500
BASE_IMAGE_RESIZEROOT=600

# export Variables
export BASE_ARCH
export DOWNLOAD_URL_CHECKSUM
export DOWNLOAD_URL_IMAGE
export BASE_ROOT_PARTITION
export BASE_IMAGE_ENLARGEROOT
export BASE_IMAGE_RESIZEROOT

#!/usr/bin/env bash
# Shebang for better file detection

# Declare Variables before exporting.
# See https://www.shellcheck.net/wiki/SC2155

# Download Base Url
DOWNLOAD_BASE_URL="https://github.com/mainsail-crew/armbian-builds/releases/latest/download"

# Base User
BASE_ADD_USER="yes"
BASE_USER="pi"
BASE_USER_PASSWORD="armbian"

# Needed while building for non rpi sbc
BASE_DISTRO="armbian"
BASE_IMAGE_RASPBIAN="no"

# Compress not needed due compression done in workflow
BASE_RELEASE_COMPRESS=no
# Modules are valid for 32bit and 64bit images
MODULES="base,pkgupgrade,udev_fix,orangepi(orangepi_net,mainsailos,klipper,is_req_preinstall,moonraker,mainsail,timelapse,crowsnest,sonar)"

# export Variables
export DOWNLOAD_BASE_URL
export BASE_ADD_USER
export BASE_USER
export BASE_USER_PASSWORD
export BASE_DISTRO
export BASE_IMAGE_RASPBIAN
export BASE_RELEASE_COMPRESS
export MODULES
